name: Build & Blob storage upload

on:
  workflow_dispatch: {}
  push:
    branches:
    - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npm run build
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      with:
        inlineScript: |
          az storage blob upload-batch --account-name vjlayouts --auth-mode key -d '$web' -s build/ --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths "/*" --profile-name "vauhtijuoksu" --name "vj-layouts" --resource-group "MC_Vauhtijuoksu-Azure-Sponsorship_vauhtijuoksu_norwayeast"
    - name: logout
      run: |
          az logout
      if: always()
